# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 16:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_task', models.IntegerField(verbose_name='Номер задания')),
                ('task', models.TextField(verbose_name='Текст задания')),
                ('answer', models.CharField(max_length=20, verbose_name='Ответ')),
                ('image', models.CharField(blank=True, max_length=100, verbose_name='Картинка к заданию')),
                ('subject_id', models.CharField(choices=[('Math', 'Математика'), ('Russian', 'Русскйи язык')], default='Math', max_length=20, verbose_name='Предмет')),
                ('test_id', models.IntegerField(blank=True, verbose_name='Номер теста')),
                ('date_pub', models.DateField(auto_now_add=True, verbose_name='Дата публикации')),
                ('flag', models.CharField(choices=[('0', 'Не проверено'), ('1', 'Проверено')], default='1', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='tasks_comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('id_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testsystem.tasks')),
            ],
        ),
        migrations.CreateModel(
            name='temp_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_test', models.IntegerField(verbose_name='Тест')),
                ('tasks', models.TextField(verbose_name='Задания')),
            ],
        ),
    ]
