# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=20, verbose_name='Предмет')),
                ('typeoftask', models.IntegerField(verbose_name='Номер задания')),
                ('nameoftask', models.CharField(max_length=50, verbose_name='Название задания')),
                ('subjecteng', models.CharField(default='math', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_task', models.IntegerField(verbose_name='Номер задания')),
                ('task', models.TextField(verbose_name='Текст задания')),
                ('answer', models.CharField(max_length=20, verbose_name='Ответ')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Картинка к заданию')),
                ('subject_id', models.CharField(choices=[('math', 'Математика'), ('russian', 'Русскйи язык')], default='math', max_length=20, verbose_name='Предмет')),
                ('test_id', models.IntegerField(blank=True, verbose_name='Номер теста')),
                ('solve', models.TextField(blank=True, verbose_name='Решение задания')),
                ('solve_image', models.ImageField(blank='True', upload_to='', verbose_name='Картинка к решению')),
                ('date_pub', models.DateField(auto_now_add=True, verbose_name='Дата публикации')),
                ('flag', models.CharField(choices=[('0', 'Не проверено'), ('1', 'Проверено')], default='1', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='tasks_comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('id_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testsystem.tasks')),
            ],
        ),
    ]
