# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='temp_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasks', models.TextField(verbose_name='Задания')),
                ('subject', models.CharField(default='math', max_length=30)),
            ],
        ),
    ]
