# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='answer_math',
            fields=[
                ('id_task', models.IntegerField(default=-1, primary_key=True, serialize=False)),
                ('answer', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='answer_russian',
            fields=[
                ('id_task', models.IntegerField(default=-1, primary_key=True, serialize=False)),
                ('answer', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='fix_test_math',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_1', models.IntegerField(default=-1)),
                ('task_2', models.IntegerField(default=-1)),
                ('task_3', models.IntegerField(default=-1)),
                ('task_4', models.IntegerField(default=-1)),
                ('task_5', models.IntegerField(default=-1)),
                ('task_6', models.IntegerField(default=-1)),
                ('task_7', models.IntegerField(default=-1)),
                ('task_8', models.IntegerField(default=-1)),
                ('task_9', models.IntegerField(default=-1)),
                ('task_10', models.IntegerField(default=-1)),
                ('task_11', models.IntegerField(default=-1)),
                ('task_12', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='fix_test_russian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_1', models.IntegerField(default=-1)),
                ('task_2', models.IntegerField(default=-1)),
                ('task_3', models.IntegerField(default=-1)),
                ('task_4', models.IntegerField(default=-1)),
                ('task_5', models.IntegerField(default=-1)),
                ('task_6', models.IntegerField(default=-1)),
                ('task_7', models.IntegerField(default=-1)),
                ('task_8', models.IntegerField(default=-1)),
                ('task_9', models.IntegerField(default=-1)),
                ('task_10', models.IntegerField(default=-1)),
                ('task_11', models.IntegerField(default=-1)),
                ('task_12', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='tasks_math',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_number', models.IntegerField(default=-1)),
                ('id_subject', models.IntegerField(default=-1)),
                ('task', models.CharField(max_length=500)),
                ('image', models.CharField(default='NULL', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='tasks_russian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_number', models.IntegerField(default=-1)),
                ('id_subject', models.IntegerField(default=-1)),
                ('task', models.CharField(max_length=500)),
                ('image', models.CharField(default='NULL', max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='comment_task',
            name='id_task',
        ),
        migrations.RemoveField(
            model_name='suggestion',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='suggestion',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='temp_test',
            name='id',
        ),
        migrations.RemoveField(
            model_name='temp_test',
            name='id_test',
        ),
        migrations.AddField(
            model_name='suggestion',
            name='id_subject',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='temp_test',
            name='id_subject',
            field=models.IntegerField(default=-1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='temp_test',
            name='id_task',
            field=models.IntegerField(default=-1),
        ),
        migrations.DeleteModel(
            name='comment_task',
        ),
        migrations.DeleteModel(
            name='tasks',
        ),
    ]
