# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsystem', '0002_auto_20170321_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_task', models.CharField(max_length=2, verbose_name='Номер задания')),
                ('subject', models.CharField(choices=[('None', 'Не выбрано'), ('Math', 'Математика'), ('Russian', 'Русскйи язык')], default='None', max_length=20, verbose_name='Предмет')),
                ('task', models.TextField(verbose_name='Текст задания')),
                ('answer', models.CharField(max_length=20, verbose_name='Ответ')),
                ('image', models.CharField(max_length=100, verbose_name='Картинка к заданию')),
                ('test_id', models.CharField(blank=True, max_length=2, verbose_name='Номер теста')),
                ('date_pub', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='answer_math',
        ),
        migrations.DeleteModel(
            name='answer_russian',
        ),
        migrations.DeleteModel(
            name='fix_test_math',
        ),
        migrations.DeleteModel(
            name='fix_test_russian',
        ),
        migrations.DeleteModel(
            name='suggestion',
        ),
        migrations.DeleteModel(
            name='tasks_math',
        ),
        migrations.DeleteModel(
            name='tasks_russian',
        ),
        migrations.DeleteModel(
            name='temp_test',
        ),
    ]
