# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsystem', '0002_auto_20170412_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='subject_id',
            field=models.CharField(choices=[('Математика', 'Математика'), ('Русскйи язык', 'Русскйи язык')], default='Математика', max_length=20, verbose_name='Предмет'),
        ),
    ]
