# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 13:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testsystem', '0003_auto_20170327_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='tasks_comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('id_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testsystem.tasks')),
            ],
        ),
        migrations.CreateModel(
            name='temp_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_test', models.CharField(max_length=5, verbose_name='Тест')),
                ('tasks', models.TextField(verbose_name='Задания')),
            ],
        ),
    ]
