# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsystem', '0003_auto_20170412_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subjecteng',
            field=models.CharField(default='math', max_length=20),
        ),
    ]
