# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsystem', '0004_tasks_comments_temp_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='image',
            field=models.CharField(blank=True, max_length=100, verbose_name='Картинка к заданию'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='test_id',
            field=models.CharField(blank=True, default='1', max_length=2, verbose_name='Номер теста'),
        ),
    ]
