# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsystem', '0004_subject_subjecteng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='subject_id',
            field=models.CharField(choices=[('math', 'Математика'), ('russian', 'Русскйи язык')], default='math', max_length=20, verbose_name='Предмет'),
        ),
    ]
