# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsystem', '0005_auto_20170327_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='flag',
            field=models.CharField(choices=[('0', 'Не проверено'), ('1', 'Проверено')], default='1', help_text='Поле для проверки задания, проверил задание - отметь единичкой ;)', max_length=20),
        ),
    ]
