# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsystem', '0006_tasks_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='subject',
            field=models.CharField(choices=[('Math', 'Математика'), ('Russian', 'Русскйи язык')], default='None', max_length=20, verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='test_id',
            field=models.IntegerField(blank=True, verbose_name='Номер теста'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='type_task',
            field=models.IntegerField(verbose_name='Номер задания'),
        ),
        migrations.AlterField(
            model_name='temp_test',
            name='id_test',
            field=models.IntegerField(verbose_name='Тест'),
        ),
    ]
