# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsystem', '0007_auto_20170327_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='date_pub',
            field=models.DateField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
    ]
